### ISSUE TITLE
Enable http/2 and HSTS

### ISSUE THREAD

**Issue by nodesocket** [fiorix/freegeoip#240]
Hello thanks for this amazing package. Wondering if we can add http/2 support and if https is enabled also send HSTS headers?

**Comment by fiorix** [comment]
Hey we already support http/2. Setting HSTS would be a great addition.

**Comment by nodesocket** [comment]
Maybe, I am misconfigured, but https://http2.pro is not showing using http2. Running latest version of freegeoip without docker.

    freegeoip -logtostdout -https ":443" -letsencrypt-cache-dir "/home/geoip" -letsencrypt -letsencrypt-hosts "geoip.mydomain.io" -letsencrypt-email "hello@mydomain.io" -quota-max 20000

**Comment by fiorix** [comment]
Ah, maybe the latest binary that I published was build before we had http/2 in Go. Let me release a new build that uses Go 1.9 and it should be there. The docker images are good already.

**Comment by fiorix** [comment]
This latest release (https://github.com/fiorix/freegeoip/releases/tag/v3.3) should support h/2. HSTS not there yet. I'd be happy to review a PR with this.

**Comment by nodesocket** [comment]
@fiorix sorry to bother, but I updated my binary to `3.3.`, deleted old Let's Encyrpt files, restarted, but still not seeing http2 support:

    Negative! geoip.commando.io does not support HTTP/2.0.
    ALPN is not supported.

```shell
➜  geoip ./freegeoip --version
freegeoip 3.3
```

**Comment by fiorix** [comment]
Oops. My bad. The custom listener we use to serve connection isn't setting the 'h2' option to enable this. Fix common soon.

Do you have any idea of how others may want to configure their HSTS? Would it work with a single cmdline param that allows you to set the value of `Strict-Transport-Security` ?

**Comment by fiorix** [comment]
Both HTTP/2 and HSTS should be available in trunk now. I haven't cut a new release yet.

**Comment by fiorix** [comment]
Updated the README with examples of how to configure HSTS.

**Comment by nodesocket** [comment]
@fiorix awesome. Can you publish a new Linux binary?

**Comment by fiorix** [comment]
Yes, I will bump it to 3.4

**Comment by fiorix** [comment]
https://github.com/fiorix/freegeoip/releases/tag/v3.4

**Comment by nodesocket** [comment]
@fiorix thanks so much for this. Much appreciated.
